### ISSUE TITLE
how to handle mutiple strings

### ISSUE THREAD

**Issue by kreutpet** [weymann/OH3-SolarForecast-Drops#1]
first of all many thanks for providing your binding.
i actually have some js-script which do the job but would prefer to handle it by a binding
i do have 2 roofs with different azimute and peak power.
according to the [description](https://articles.solcast.com.au/en/articles/2887438-how-do-i-create-a-multiple-azimuth-rooftop-solar-site) this would require to define an additional site.

the binding would support to create multiple sites but it would not allow to accumulate the data for the multiple sites reflecting actually a single site. It would be interesting to discuss how to us the binding but still get the summed forecast of my roofs at one site.

thx
peter

**Comment by weymann** [comment]
Ok, I think I see the problem here. The Solcast `site` definition is not identical to `sc-site` from the binding. The word _site_ for Solcast and Forecast.Solar is referring to one location, e.g. your home location.

Create one [Bridge](https://github.com/weymann/OH3-SolarForecast-Drops#solcast-bridge-configuration) `sc-site` with your Solcast API Key
Create multiple [Planes ](https://github.com/weymann/OH3-SolarForecast-Drops#solcast-plane-configuration) `sc-plane`  each attached to the previous defined Bridge using the Solcast ResourceId.

Values are now reported for each `sc-plane` and the `sc-site` Bridge sums all up.

**Comment by kreutpet** [comment]
Many thanks. I separated the up the roof tops into different sc-planes.
I assume that the 50 free API call are now accumulates by both sc-planes.
I will set the refresh rate to 60 minutes , that should be ok for the 50 free call 
in the next days i will verify if all data are coming

**Comment by weymann** [comment]
Right, one sc-site, 2 sc-planes. 

Sadly you need 2 calls per plane
- one for "now and past"
- one for "forecast"

So you'll end up with refreshinterval of 120 minutes, see here in readme: 
https://github.com/weymann/OH3-SolarForecast-Drops#solcast-plane-configuration
